###########################################################
# ******************** System env *************************
###########################################################
sys:
  env:
    cd: L


###########################################################
# ******************** server *************************
###########################################################
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    servlet:
      encoding:
        force-response: true

###########################################################
# ******************** pid3 *************************
###########################################################
spring:
  pid:
    file: /apprun/boilderplate/boilderplate.pid


