spring:
  profiles:
    active: local

########################################################
# ************ HTTP/HTTPS ***********
########################################################
server:
  port: 8080
  undertow:
    io-threads: 4
    worker-threads: 32
    buffer-size: 1024
    direct-buffers: true
  error:
    whitelabel:
      enabled: false
    servlet:
      encoding:
        force-response: true

# Configure the server to run with SSL/TLS and using HTTPS
#  port: 8443
#  ssl:
#    key-store: classpath:your_own_cert.jks.sample
#    key-store-password: <your-ssl-keystore-password>
#    key-password: <your-ssl-key-password>

########################################################
# ************ Actuator Security Settings ***********
########################################################
management:
  endpoints:
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include:
          - "info"
          - "health"
    server:

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    url: /docs/open-api-3.0.1.json
    path: /docs/swagger