###########################################################
# ******************** System env *************************
###########################################################
sys:
  env:
    cd: L

###########################################################
# ******************** pid3 *************************
###########################################################
spring:
  pid:
    file: /apprun/boilderplate/boilderplate.pid


